In [1]:
import numpy as np
import cv2


In [2]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
image = cv2.imread('team3.jpg')
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [3]:
#Here faces is a Numpy ndarray
faces = face_cascade.detectMultiScale(grayImage)

#Just to confirm the type of the output, we use Python’s type function to check the type of the returned object
print (type(faces))
print (faces)

<class 'numpy.ndarray'>
[[1739  379  302  302]
 [1033  380  323  323]
 [2448  407  316  316]
 [3118  403  310  310]
 [4426  610  329  329]
 [ 553  641  317  317]
 [3908  719  338  338]
 [2489  809  119  119]
 [3182  832  107  107]
 [2236 1602  352  352]
 [2987 1619  338  338]
 [1701 1758  310  310]
 [3746 1868  400  400]
 [1502 1321   64   64]
 [1532 1533   57   57]
 [ 932 1751  136  136]
 [2368 2133  102  102]
 [1767 2068   91   91]
 [1702 2196   85   85]
 [1952 2625   70   70]]


##### We can also know more about our output by calling the shape method on our array, which will return its dimensions. As we will see, we will get a matrix of N rows and 4 columns, being N the number of faces detected and 4 the dimensions of the rectangle of each face.

In [4]:
print (faces.shape)

(20, 4)


In [5]:
print ("Number of faces detected: " + str(faces.shape[0]))

Number of faces detected: 20


In [6]:
#draw the rectangles around the faces in our original image
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)

In [7]:
#for text in image
cv2.rectangle(image, ((0,image.shape[0]-25)),(270, image.shape[0]), (255,255,255), -1)
cv2.putText(image, "Number of faces detected: " + str(faces.shape[0]), (0,image.shape[0] -10), cv2.FONT_HERSHEY_TRIPLEX, 0.5, (0,0,0), 1)

array([[[158, 144, 121],
        [158, 144, 121],
        [159, 145, 122],
        ...,
        [119, 123, 112],
        [119, 123, 112],
        [119, 123, 112]],

       [[157, 143, 120],
        [158, 144, 121],
        [158, 144, 121],
        ...,
        [119, 123, 112],
        [119, 123, 112],
        [119, 123, 112]],

       [[160, 144, 121],
        [160, 144, 121],
        [160, 144, 121],
        ...,
        [119, 123, 112],
        [119, 123, 112],
        [119, 123, 112]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [158, 162, 180],
        [160, 162, 180],
        [160, 162, 180]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [158, 162, 180],
        [160, 163, 178],
        [160, 163, 178]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [158, 162, 180],
        [160, 163, 178],
        [159, 162, 177]]

In [ ]:
cv2.imshow('Image with faces',image)
cv2.waitKey(0)
cv2.destroyAllWindows()